language: swift
os: osx
osx_image: xcode11.2
xcode_workspace: Travis_Test.xcworkspace
xcode_scheme: CI
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
notifications:
email:
  recipients:
    - j.batista.damasceno@icloud.com
  on_success: always # default: change
  on_failure: always # default: always
