language:
  - swift
osx_image: xcode11.2
script:
  - xcodebuild clean build test -workspace Travis_Test.xcworkspace -scheme "CI" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 8,' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
